server:
  port: 8040
springdoc:
  swagger-ui:
    path: /

spring:
  application:
    name: application-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: assignment-service
            uri: lb://assignment-service
            predicates:
              - Path=/api/v1/assignments/**

          - id: report-service
            uri: lb://report-service
            predicates:
              - Path=/api/v1/reports/**

          - id: discovery-server
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/

          - id: discovery-server-static
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE

